const quotes = [
  "Believe you can and you're halfway there.",
  "The expert in anything was once a beginner.",
  "Success is the sum of small efforts repeated daily.",
  "Focus on progress, not perfection.",
  "Your only limit is you.",
  "Start where you are. Use what you have. Do what you can.",
  "Study smart, not just hard.",
  "Every accomplishment starts with the decision to try.",
  "The secret to getting ahead is getting started.",
  "Don't watch the clock; do what it does. Keep going.",
  "Consistency is key to mastery.",
  "Small daily improvements lead to stunning results.",
  "Knowledge is power, but action is progress.",
  "You don't have to be great to start, but you have to start to be great.",
  "Success doesn't come from what you do occasionally, but what you do consistently.",
  "The harder you work, the luckier you get.",
  "Dream big, start small, act now.",
  "Discipline is choosing between what you want now and what you want most.",
  "Your mind is a powerful thing. Fill it with positive thoughts.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Procrastination is the thief of time.",
  "Do something today that your future self will thank you for.",
  "Study like there's no tomorrow.",
  "Excellence is not a skill, it's an attitude.",
  "The only way to do great work is to love what you do.",
  "Learning never exhausts the mind.",
  "Education is the passport to the future.",
  "Strive for progress, not perfection.",
  "Your limitation is only your imagination.",
  "Great things never come from comfort zones.",
  "Success is not final, failure is not fatal.",
  "Work hard in silence, let success make the noise.",
  "The future depends on what you do today.",
  "Stay focused and never give up.",
  "You are capable of amazing things.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Study now, shine later.",
  "Push yourself because no one else is going to do it for you.",
  "A little progress each day adds up to big results.",
  "The only impossible journey is the one you never begin.",
  "Study today, succeed tomorrow.",
  "Your potential is endless.",
  "Be stronger than your excuses.",
  "It always seems impossible until it's done.",
  "Wake up with determination, go to bed with satisfaction.",
  "Focus on being productive instead of busy.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Success is built one day at a time.",
  "Make each day your masterpiece.",
  "The struggle you're in today is developing the strength you need tomorrow.",
  "Learn from yesterday, live for today, hope for tomorrow.",
  "Stay patient and trust the journey.",
  "Hard work beats talent when talent doesn't work hard.",
  "The key to success is consistency.",
  "Every expert was once a beginner who never gave up.",
  "Success is not about being the best, it's about being better than you were yesterday.",
  "Study breaks are important, but so is staying focused.",
  "You're braver than you believe, stronger than you seem, smarter than you think.",
  "Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus.",
  "Motivation gets you started, habit keeps you going.",
];

export { quotes };
